/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Complaint {
  'id' : string,
  'media' : Array<Media>,
  'status' : ComplaintStatus,
  'issueType' : IssueType,
  'description' : string,
  'statusHistory' : Array<ComplaintStatus>,
  'anonymous' : boolean,
  'timestamp' : Time,
  'reporter' : [] | [Principal],
  'location' : Location,
}
export type ComplaintStatus = { 'escalated' : null } |
  { 'underReview' : null } |
  { 'actionTaken' : null } |
  { 'received' : null };
export type IssueType = { 'trafficViolation' : null } |
  { 'garbage' : null } |
  { 'publicNuisance' : null } |
  { 'tobaccoSpit' : null };
export interface Location {
  'latitude' : number,
  'postalCode' : [] | [string],
  'longitude' : number,
  'address' : [] | [string],
}
export interface Media {
  'url' : string,
  'timestamp' : Time,
  'mediaType' : MediaType,
  'location' : Location,
}
export type MediaType = { 'video' : null } |
  { 'image' : null };
export type Time = bigint;
export interface UserProfile {
  'badgeLevel' : bigint,
  'name' : string,
  'role' : string,
  'civicScore' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'fileComplaint' : ActorMethod<
    [IssueType, string, Location, Array<Media>, boolean],
    Complaint
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComplaint' : ActorMethod<[string], Complaint>,
  'getComplaintsByStatus' : ActorMethod<[ComplaintStatus], Array<Complaint>>,
  'getMyComplaints' : ActorMethod<[], Array<Complaint>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateComplaintStatus' : ActorMethod<[string, ComplaintStatus], undefined>,
  'uploadMedia' : ActorMethod<[MediaType, string, Location], Media>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];