/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const IssueType = IDL.Variant({
  'trafficViolation' : IDL.Null,
  'garbage' : IDL.Null,
  'publicNuisance' : IDL.Null,
  'tobaccoSpit' : IDL.Null,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'postalCode' : IDL.Opt(IDL.Text),
  'longitude' : IDL.Float64,
  'address' : IDL.Opt(IDL.Text),
});
export const Time = IDL.Int;
export const MediaType = IDL.Variant({
  'video' : IDL.Null,
  'image' : IDL.Null,
});
export const Media = IDL.Record({
  'url' : IDL.Text,
  'timestamp' : Time,
  'mediaType' : MediaType,
  'location' : Location,
});
export const ComplaintStatus = IDL.Variant({
  'escalated' : IDL.Null,
  'underReview' : IDL.Null,
  'actionTaken' : IDL.Null,
  'received' : IDL.Null,
});
export const Complaint = IDL.Record({
  'id' : IDL.Text,
  'media' : IDL.Vec(Media),
  'status' : ComplaintStatus,
  'issueType' : IssueType,
  'description' : IDL.Text,
  'statusHistory' : IDL.Vec(ComplaintStatus),
  'anonymous' : IDL.Bool,
  'timestamp' : Time,
  'reporter' : IDL.Opt(IDL.Principal),
  'location' : Location,
});
export const UserProfile = IDL.Record({
  'badgeLevel' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'civicScore' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'fileComplaint' : IDL.Func(
      [IssueType, IDL.Text, Location, IDL.Vec(Media), IDL.Bool],
      [Complaint],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComplaint' : IDL.Func([IDL.Text], [Complaint], ['query']),
  'getComplaintsByStatus' : IDL.Func(
      [ComplaintStatus],
      [IDL.Vec(Complaint)],
      ['query'],
    ),
  'getMyComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateComplaintStatus' : IDL.Func([IDL.Text, ComplaintStatus], [], []),
  'uploadMedia' : IDL.Func([MediaType, IDL.Text, Location], [Media], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const IssueType = IDL.Variant({
    'trafficViolation' : IDL.Null,
    'garbage' : IDL.Null,
    'publicNuisance' : IDL.Null,
    'tobaccoSpit' : IDL.Null,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'postalCode' : IDL.Opt(IDL.Text),
    'longitude' : IDL.Float64,
    'address' : IDL.Opt(IDL.Text),
  });
  const Time = IDL.Int;
  const MediaType = IDL.Variant({ 'video' : IDL.Null, 'image' : IDL.Null });
  const Media = IDL.Record({
    'url' : IDL.Text,
    'timestamp' : Time,
    'mediaType' : MediaType,
    'location' : Location,
  });
  const ComplaintStatus = IDL.Variant({
    'escalated' : IDL.Null,
    'underReview' : IDL.Null,
    'actionTaken' : IDL.Null,
    'received' : IDL.Null,
  });
  const Complaint = IDL.Record({
    'id' : IDL.Text,
    'media' : IDL.Vec(Media),
    'status' : ComplaintStatus,
    'issueType' : IssueType,
    'description' : IDL.Text,
    'statusHistory' : IDL.Vec(ComplaintStatus),
    'anonymous' : IDL.Bool,
    'timestamp' : Time,
    'reporter' : IDL.Opt(IDL.Principal),
    'location' : Location,
  });
  const UserProfile = IDL.Record({
    'badgeLevel' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'civicScore' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'fileComplaint' : IDL.Func(
        [IssueType, IDL.Text, Location, IDL.Vec(Media), IDL.Bool],
        [Complaint],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComplaint' : IDL.Func([IDL.Text], [Complaint], ['query']),
    'getComplaintsByStatus' : IDL.Func(
        [ComplaintStatus],
        [IDL.Vec(Complaint)],
        ['query'],
      ),
    'getMyComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateComplaintStatus' : IDL.Func([IDL.Text, ComplaintStatus], [], []),
    'uploadMedia' : IDL.Func([MediaType, IDL.Text, Location], [Media], []),
  });
};

export const init = ({ IDL }) => { return []; };