/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    latitude: number;
    postalCode?: string;
    longitude: number;
    address?: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Complaint {
    id: string;
    media: Array<Media>;
    status: ComplaintStatus;
    issueType: IssueType;
    description: string;
    statusHistory: Array<ComplaintStatus>;
    anonymous: boolean;
    timestamp: Time;
    reporter?: Principal;
    location: Location;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Media {
    url: string;
    timestamp: Time;
    mediaType: MediaType;
    location: Location;
}
export interface UserProfile {
    badgeLevel: bigint;
    name: string;
    role: string;
    civicScore: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ComplaintStatus {
    escalated = "escalated",
    underReview = "underReview",
    actionTaken = "actionTaken",
    received = "received"
}
export enum IssueType {
    trafficViolation = "trafficViolation",
    garbage = "garbage",
    publicNuisance = "publicNuisance",
    tobaccoSpit = "tobaccoSpit"
}
export enum MediaType {
    video = "video",
    image = "image"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    fileComplaint(issueType: IssueType, description: string, location: Location, media: Array<Media>, anonymous: boolean): Promise<Complaint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getComplaint(complaintId: string): Promise<Complaint>;
    getComplaintsByStatus(status: ComplaintStatus): Promise<Array<Complaint>>;
    getMyComplaints(): Promise<Array<Complaint>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateComplaintStatus(complaintId: string, newStatus: ComplaintStatus): Promise<void>;
    uploadMedia(mediaType: MediaType, url: string, location: Location): Promise<Media>;
}
import type { Complaint as _Complaint, ComplaintStatus as _ComplaintStatus, IssueType as _IssueType, Location as _Location, Media as _Media, MediaType as _MediaType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async fileComplaint(arg0: IssueType, arg1: string, arg2: Location, arg3: Array<Media>, arg4: boolean): Promise<Complaint> {
        if (this.processError) {
            try {
                const result = await this.actor.fileComplaint(to_candid_IssueType_n10(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_Location_n12(this._uploadFile, this._downloadFile, arg2), to_candid_vec_n14(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_Complaint_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fileComplaint(to_candid_IssueType_n10(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_Location_n12(this._uploadFile, this._downloadFile, arg2), to_candid_vec_n14(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_Complaint_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComplaint(arg0: string): Promise<Complaint> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplaint(arg0);
                return from_candid_Complaint_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplaint(arg0);
            return from_candid_Complaint_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComplaintsByStatus(arg0: ComplaintStatus): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplaintsByStatus(to_candid_ComplaintStatus_n38(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplaintsByStatus(to_candid_ComplaintStatus_n38(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyComplaints(): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyComplaints();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyComplaints();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateComplaintStatus(arg0: string, arg1: ComplaintStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateComplaintStatus(arg0, to_candid_ComplaintStatus_n38(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateComplaintStatus(arg0, to_candid_ComplaintStatus_n38(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadMedia(arg0: MediaType, arg1: string, arg2: Location): Promise<Media> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadMedia(to_candid_MediaType_n17(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_Location_n12(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Media_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadMedia(to_candid_MediaType_n17(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_Location_n12(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Media_n22(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ComplaintStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ComplaintStatus): ComplaintStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Complaint_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Complaint): Complaint {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_IssueType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IssueType): IssueType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Location_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Location): Location {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_MediaType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaType): MediaType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Media_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Media): Media {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    media: Array<_Media>;
    status: _ComplaintStatus;
    issueType: _IssueType;
    description: string;
    statusHistory: Array<_ComplaintStatus>;
    anonymous: boolean;
    timestamp: _Time;
    reporter: [] | [Principal];
    location: _Location;
}): {
    id: string;
    media: Array<Media>;
    status: ComplaintStatus;
    issueType: IssueType;
    description: string;
    statusHistory: Array<ComplaintStatus>;
    anonymous: boolean;
    timestamp: Time;
    reporter?: Principal;
    location: Location;
} {
    return {
        id: value.id,
        media: from_candid_vec_n21(_uploadFile, _downloadFile, value.media),
        status: from_candid_ComplaintStatus_n29(_uploadFile, _downloadFile, value.status),
        issueType: from_candid_IssueType_n31(_uploadFile, _downloadFile, value.issueType),
        description: value.description,
        statusHistory: from_candid_vec_n33(_uploadFile, _downloadFile, value.statusHistory),
        anonymous: value.anonymous,
        timestamp: value.timestamp,
        reporter: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.reporter)),
        location: from_candid_Location_n26(_uploadFile, _downloadFile, value.location)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    timestamp: _Time;
    mediaType: _MediaType;
    location: _Location;
}): {
    url: string;
    timestamp: Time;
    mediaType: MediaType;
    location: Location;
} {
    return {
        url: value.url,
        timestamp: value.timestamp,
        mediaType: from_candid_MediaType_n24(_uploadFile, _downloadFile, value.mediaType),
        location: from_candid_Location_n26(_uploadFile, _downloadFile, value.location)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: number;
    postalCode: [] | [string];
    longitude: number;
    address: [] | [string];
}): {
    latitude: number;
    postalCode?: string;
    longitude: number;
    address?: string;
} {
    return {
        latitude: value.latitude,
        postalCode: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.postalCode)),
        longitude: value.longitude,
        address: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.address))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    image: null;
}): MediaType {
    return "video" in value ? MediaType.video : "image" in value ? MediaType.image : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    escalated: null;
} | {
    underReview: null;
} | {
    actionTaken: null;
} | {
    received: null;
}): ComplaintStatus {
    return "escalated" in value ? ComplaintStatus.escalated : "underReview" in value ? ComplaintStatus.underReview : "actionTaken" in value ? ComplaintStatus.actionTaken : "received" in value ? ComplaintStatus.received : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trafficViolation: null;
} | {
    garbage: null;
} | {
    publicNuisance: null;
} | {
    tobaccoSpit: null;
}): IssueType {
    return "trafficViolation" in value ? IssueType.trafficViolation : "garbage" in value ? IssueType.garbage : "publicNuisance" in value ? IssueType.publicNuisance : "tobaccoSpit" in value ? IssueType.tobaccoSpit : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Media>): Array<Media> {
    return value.map((x)=>from_candid_Media_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ComplaintStatus>): Array<ComplaintStatus> {
    return value.map((x)=>from_candid_ComplaintStatus_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Complaint>): Array<Complaint> {
    return value.map((x)=>from_candid_Complaint_n19(_uploadFile, _downloadFile, x));
}
function to_candid_ComplaintStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ComplaintStatus): _ComplaintStatus {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_IssueType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IssueType): _IssueType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Location_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Location): _Location {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_MediaType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): _MediaType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_Media_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Media): _Media {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: number;
    postalCode?: string;
    longitude: number;
    address?: string;
}): {
    latitude: number;
    postalCode: [] | [string];
    longitude: number;
    address: [] | [string];
} {
    return {
        latitude: value.latitude,
        postalCode: value.postalCode ? candid_some(value.postalCode) : candid_none(),
        longitude: value.longitude,
        address: value.address ? candid_some(value.address) : candid_none()
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    timestamp: Time;
    mediaType: MediaType;
    location: Location;
}): {
    url: string;
    timestamp: _Time;
    mediaType: _MediaType;
    location: _Location;
} {
    return {
        url: value.url,
        timestamp: value.timestamp,
        mediaType: to_candid_MediaType_n17(_uploadFile, _downloadFile, value.mediaType),
        location: to_candid_Location_n12(_uploadFile, _downloadFile, value.location)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IssueType): {
    trafficViolation: null;
} | {
    garbage: null;
} | {
    publicNuisance: null;
} | {
    tobaccoSpit: null;
} {
    return value == IssueType.trafficViolation ? {
        trafficViolation: null
    } : value == IssueType.garbage ? {
        garbage: null
    } : value == IssueType.publicNuisance ? {
        publicNuisance: null
    } : value == IssueType.tobaccoSpit ? {
        tobaccoSpit: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): {
    video: null;
} | {
    image: null;
} {
    return value == MediaType.video ? {
        video: null
    } : value == MediaType.image ? {
        image: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ComplaintStatus): {
    escalated: null;
} | {
    underReview: null;
} | {
    actionTaken: null;
} | {
    received: null;
} {
    return value == ComplaintStatus.escalated ? {
        escalated: null
    } : value == ComplaintStatus.underReview ? {
        underReview: null
    } : value == ComplaintStatus.actionTaken ? {
        actionTaken: null
    } : value == ComplaintStatus.received ? {
        received: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Media>): Array<_Media> {
    return value.map((x)=>to_candid_Media_n15(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
